### ISSUE TITLE
Traversal : Improve performance and memory usage of tree traversal

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#2]
**TODO**
- Avoid new keyword in update
- Reuse functions as much as possible

**Places to Improve**
- [ ] Promise callbacks
  - https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/PriorityQueue.js#L16-L36
  - https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/PriorityQueue.js#L57-L97
  - https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/ThreeB3DMLoader.js#L10-L14
  - https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/TilesRenderer.js#L514-L719
- [x] Avoid unnecessary multiplication
  - [for obbMat](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/ThreeTilesRenderer.js#L449-L453)
- [x] Improve LRUCache performance when marking items as used or removing them
- [x] Cache all transforms in the appropriate frame so _no_ matrix calculations have to happen in the update loop.
- [x] Change the setVisible function to not add or remove from the scene object because that can be slow -- update the children array all at once after update has run.
