### ISSUE TITLE
Support of Implicit Tiling

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#608]
[Implicit Tiling](https://docs.ogc.org/cs/22-025r4/22-025r4.html#toc31)

I wish to implement the support of Implicit Tiling (introduced in 3D Tiles 1.1). It has been discussed in different issues but is there already a plan or ideas how to do it ?

I've seen that in Cesium, the implicit tiling is directly managed from [Cesium3DTileset](https://github.com/CesiumGS/cesium/blob/7b93161da1cc03bdc796b204e7aa51fb7acebf04/packages/engine/Source/Scene/Cesium3DTileset.js#L2259), which is kind of the equivalent of `TilesRendererBase` here. Do you think I should do a similar implementation ?

I've also noticed the recent addition of plugins, will it be a better idea to implement a ImplicitTilingPlugin with the necessary hooks ?
What is your take on this topic ?

Do you have any tips/warnings to help me in this new implicit tiling support in 3DTilesRendererJS ?

I'll first begin by the parsing of the .subtree files.

Thank you

**Comment by gkjohnson** [comment]
Hello! A contribution to support implicit tiling would be great - there hasn't been thought put into this feature yet, though, so your help here would be appreciated. As far as I understand the feature requires support for something akin to "virtual" tile children that have implicitly calculated bounding volumes and content URLs. Is that a reasonable summary?

> Do you think I should do a similar implementation ?

I'm less familiar with the Cesium3DTileset implementation for this. Do you mind giving a brief description of what a similar implementation would look like?

> Do you have any tips/warnings to help me in this new implicit tiling support in 3DTilesRendererJS ?

I think one of the larger things that will need to be considered here is how to handle these "virtual" child tiles since there's a lot of intermediate information stored on the tile object for the sake of traversing and loading data. I was originally thinking we'd want to avoid generating child tile representations for each implicit child but that may be an okay place to start since we'll ultimately have to create an object to store the intermediate data, anyway - whether it's stored as a child or somewhere else. An optimization here could be deleting all child objects to free up memory as soon as a tile is unloaded as the camera moves.

I'm curious as how Cesium is handling this already if you know, though.

> I've also noticed the recent addition of plugins, will it be a better idea to implement a ImplicitTilingPlugin with the necessary hooks ?
> What is your take on this topic ?

I think this should be enabled by default but using a plugin could help compartmentalize the logic a big more - once we have a more solid idea of how this should be implemented I think it will be easier to say.

**Comment by AnthonyGlt** [comment]
Thank you for the answer
I have a draft of an implementation. I'll open a MR soon, once the code is cleaner.
I'll explain the structure, i've tried to keep intact the existing TilesRenderer architecture.
My MR will concern a limited scope of the implicit tiling for now, depending on the time I have to work on it.

I'll bring more infos in the MR, i've just wanted to notice you that I was still on it and I have good results  :+1:

**Comment by AnthonyGlt** [comment]
The MR :
https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/650

@gkjohnson

**Comment by AnthonyGlt** [comment]
**TODOs:**

- [ ] OCTREE support. Doesn't seem to difficult
- [ ] Sphere bounding volume support. Not to difficult. I only did the Region & Box
- [ ] [Subtree JSON Format](https://docs.ogc.org/cs/22-025r4/22-025r4.html#toc38) support. I only did the Binary format
- [ ] Metadata support
- [ ] External support (e.g The buffer could be stored in another file)
- [ ] Extension `3DTILES_implicit_tiling` support. For now the tileset must have the object implicitTiling as follows:
```
"implicitTiling": {
      "subdivisionScheme": "QUADTREE",
      "availableLevels": 21,
      "subtreeLevels": 7,
      "subtrees": {
        "uri": "subtrees/{level}/{x}/{y}.json"
      }
    }

```
- [ ] Multiple Contents support. Only one content is supported for now
- [ ] ImplicitTiling defined in children. Only the one in root is supported

**Comment by gkjohnson** [comment]
If you're looking for other, more complete tile sets to try out and test - these Cesium ion tile sets include implicit tiling roots:

- asset id `2389063`
- asset id `2389064`

See [this](https://sandcastle.cesium.com/?src=3D%20Tiles%201.1%20CDB%20Yemen.html) Cesium sandbox demo.

**Comment by Om-singhaI** [comment]
Hi @gkjohnson, I would like to pick up some of the remaining items here, and I would appreciate a sanity check on scope before writing anything.

**Subtree JSON format.** I would start here, because the core already does most of the routing. `requestTileContents` parses a `.json` response and only treats it as an external tileset when the payload has a `root` property, so a parsed subtree object already falls through to `plugin.parseTile`. That leaves splitting `SUBTREELoader.parse` so the binary path and an object path share the same subtree parsing (replacing the `// todo here : handle json` comment), plus giving `ImplicitTilingPlugin` a reliable way to recognise a subtree tile instead of testing for a `.subtree` extension. Would you be happy with the plugin setting a marker in `tile.internal` during `preprocessNode` when it generates a content uri from `implicitTiling.subtrees.uri`, or would you rather that discrimination live elsewhere?

**The 3DTILES_implicit_tiling extension form.** I would normalise the extension object into the 1.1 `implicitTiling` object in `preprocessNode`, unless you would prefer the two paths kept separate.

**One correction on the checklist.** The item "Sphere bounding volume support" reads as a subdivision rule, but the spec says sphere bounding volumes are disallowed for implicit tiling precisely because they cannot be divided into a quadtree or octree. I think that item is really the `TILE_BOUNDING_SPHERE` metadata semantic, so I would fold it into the metadata work rather than doing it standalone. Please tell me if I have that wrong.

**Subtree and tile metadata.** The property table readers under `src/three/plugins/gltf/metadata` already implement the binary table format and have no three.js dependency. Would you want those lifted into core so the glTF and tileset metadata paths share one implementation, or would you rather I write a separate minimal reader in core to avoid churn in the glTF path?

**Multiple contents** is the one item I do not want to guess at. A single `tile.content`, one loading state and one cache entry per tile are assumed across `TilesRendererBase`, the LRU accounting and the scene management, so the change is not local to this plugin. Is that something you would rather drive yourself? If you are open to an outside version, would expanding a `contents` array into virtual child tiles, so the one content per tile invariant still holds, be an acceptable shape?

I would send these as small separate PRs in that order rather than one large one, with vitest coverage for the subtree parsing and the uri templating. I noticed there is currently no test coverage for implicit tiling at all, so I would add fixtures based on the Cesium spec sample data.

If any of this is already on your own list, or the maintenance cost is not worth it right now, I am happy to take only the parts that are actually useful to you.

**Comment by gkjohnson** [comment]
@Om-singhaI I appreciate the interest but are planning to use these changes or just looking for something to work on? I ask because all the plans you have listed are copy and pasted from an AI. I don't mind using AI for this work but I want to make sure that someone is working on it that understands the intent of the changes being made. Otherwise it puts a much larger burden on me in the review process.

**Comment by Om-singhaI** [comment]
@gkjohnson Sorry about that.

I'm an open source contributor rather than a user of the library. I came across this project, thought it was genuinely impressive work, and wanted to put my skills toward something with real scope instead of a typo fix. The 3D and hardware side is what I actually spend my time on, so it felt like a good match.

On the comment itself: I've never written a proposal like that before and I wanted it to come across as professional and thought through, so I used an assistant to draft it. It made more work for you rather than less, which was the opposite of what I was going for. Going forward I'll keep my issue comments and PR descriptions short and plain so they're quicker to get through.

One correction while I'm here. I said the sphere bounding volume item was "really" the metadata semantic, which I was guessing at. Looking properly, the TODO sits on `getTileBoundingVolume` and it only branches region and box, so it did mean subdivision like it says. The spec disallows it there anyway, "Sphere bounding volumes are disallowed, as these cannot be divided into a quadtree or octree", so there isn't much to build for that one either way.

Happy to start with something smaller if you'd rather see how I work before I take on subtree JSON.

**Comment by gkjohnson** [comment]
Hi @Om-singhaI - sorry for the delay. If you'd like to submit a PR to address one of the missing features for implicit tiling that would be appreciated. Lets keep changes small to start and make sure we have a good method for testing them.
